
import { fitPX } from './util';
import { isNumber } from 'lodash';

export default {

    clrBlack: { color: '#000' },
    clrWhite: { color: '#fff' },
    clr333: { color: '#333' },
    clr999: { color: '#999' },
    clrB2: { color: '#b2b2b2' },

    bg: function (str) {
        return { backgroundColor: str }
    },
    bgRgba: function (r = 0, g = 0, b = 0, a = 1) {
        let rgba = 'rgba(' + r + ',' + g + ',' + b + ',' + a + ')';

        return {
            backgroundColor: rgba
        }
    },
    bgBlack: { backgroundColor: '#000' },
    bgBlue: { backgroundColor: 'blue' },
    bgRed: { backgroundColor: 'red' },
    bgTrans: { backgroundColor: 'transparent' },
    bgGreen: { backgroundColor: '#008000' },
    bgWhite: { backgroundColor: '#fff' },
    bgYellow: { backgroundColor: '#FFFF00' },

    flexAuto: { flex: 1 },
    flexRow: { flexDirection: 'row' },
    flexColumn: { flexDirection: 'column' },
    flexCenter: { justifyContent: 'center', alignItems: 'center' },

    // justify-content
    justStart: { justifyContent: 'flex-start' },
    justEnd: { justifyContent: 'flex-end' },
    justCenter: { justifyContent: 'center' },
    justBetween: { justifyContent: 'space-between' },
    justAround: { justifyContent: 'space-around' },

    // align-content
    alonStart: { alignContent: 'flex-start' },
    alonEnd: { alignContent: 'flex-end' },
    alonCenter: { alignContent: 'center' },
    alonBetween: { alignContent: 'space-between' },
    alonAround: { alignContent: 'space-around' },
    alonStretch: { alignContent: 'stretch' },

    // align-items
    algnStart: { alignItems: 'flex-start' },
    algnEnd: { alignItems: 'flex-end' },
    algnCenter: { alignItems: 'center' },
    algnBaseline: { alignItems: 'baseline' },
    algnStretch: { alignItems: 'stretch' },

    // align-self
    selfAuto: { alignSelf: 'auto' },
    selfStart: { alignSelf: 'flex-start' },
    selfEnd: { alignSelf: 'flex-end' },
    selfCenter: { alignSelf: 'center' },
    selfBaseline: { alignSelf: 'baseline' },
    selfStretch: { alignSelf: 'stretch' },

    fz: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            fontSize: fitPX(number)
        }
    },
    fz0: { fontSize: fitPX(0) },
    fz1: { fontSize: fitPX(1) },
    fz2: { fontSize: fitPX(2) },
    fz3: { fontSize: fitPX(3) },
    fz4: { fontSize: fitPX(4) },
    fz5: { fontSize: fitPX(5) },
    fz6: { fontSize: fitPX(6) },
    fz7: { fontSize: fitPX(7) },
    fz8: { fontSize: fitPX(8) },
    fz9: { fontSize: fitPX(9) },
    fz10: { fontSize: fitPX(10) },
    fz11: { fontSize: fitPX(11) },
    fz12: { fontSize: fitPX(12) },
    fz13: { fontSize: fitPX(13) },
    fz14: { fontSize: fitPX(14) },
    fz15: { fontSize: fitPX(15) },
    fz16: { fontSize: fitPX(16) },
    fz17: { fontSize: fitPX(17) },
    fz18: { fontSize: fitPX(18) },
    fz19: { fontSize: fitPX(19) },
    fz20: { fontSize: fitPX(20) },
    fz21: { fontSize: fitPX(21) },
    fz22: { fontSize: fitPX(22) },
    fz23: { fontSize: fitPX(23) },
    fz24: { fontSize: fitPX(24) },
    fz25: { fontSize: fitPX(25) },
    fz26: { fontSize: fitPX(26) },
    fz27: { fontSize: fitPX(27) },
    fz28: { fontSize: fitPX(28) },
    fz29: { fontSize: fitPX(29) },
    fz30: { fontSize: fitPX(30) },

    fz_0: { fontSize: fitPX(-0) },
    fz_1: { fontSize: fitPX(-1) },
    fz_2: { fontSize: fitPX(-2) },
    fz_3: { fontSize: fitPX(-3) },
    fz_4: { fontSize: fitPX(-4) },
    fz_5: { fontSize: fitPX(-5) },
    fz_6: { fontSize: fitPX(-6) },
    fz_7: { fontSize: fitPX(-7) },
    fz_8: { fontSize: fitPX(-8) },
    fz_9: { fontSize: fitPX(-9) },
    fz_10: { fontSize: fitPX(-10) },
    fz_11: { fontSize: fitPX(-11) },
    fz_12: { fontSize: fitPX(-12) },
    fz_13: { fontSize: fitPX(-13) },
    fz_14: { fontSize: fitPX(-14) },
    fz_15: { fontSize: fitPX(-15) },
    fz_16: { fontSize: fitPX(-16) },
    fz_17: { fontSize: fitPX(-17) },
    fz_18: { fontSize: fitPX(-18) },
    fz_19: { fontSize: fitPX(-19) },
    fz_20: { fontSize: fitPX(-20) },
    fz_21: { fontSize: fitPX(-21) },
    fz_22: { fontSize: fitPX(-22) },
    fz_23: { fontSize: fitPX(-23) },
    fz_24: { fontSize: fitPX(-24) },
    fz_25: { fontSize: fitPX(-25) },
    fz_26: { fontSize: fitPX(-26) },
    fz_27: { fontSize: fitPX(-27) },
    fz_28: { fontSize: fitPX(-28) },
    fz_29: { fontSize: fitPX(-29) },
    fz_30: { fontSize: fitPX(-30) },

    lh: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            lineHeight: fitPX(number)
        }
    },
    lh0: { lineHeight: fitPX(0) },
    lh1: { lineHeight: fitPX(1) },
    lh2: { lineHeight: fitPX(2) },
    lh3: { lineHeight: fitPX(3) },
    lh4: { lineHeight: fitPX(4) },
    lh5: { lineHeight: fitPX(5) },
    lh6: { lineHeight: fitPX(6) },
    lh7: { lineHeight: fitPX(7) },
    lh8: { lineHeight: fitPX(8) },
    lh9: { lineHeight: fitPX(9) },
    lh10: { lineHeight: fitPX(10) },
    lh11: { lineHeight: fitPX(11) },
    lh12: { lineHeight: fitPX(12) },
    lh13: { lineHeight: fitPX(13) },
    lh14: { lineHeight: fitPX(14) },
    lh15: { lineHeight: fitPX(15) },
    lh16: { lineHeight: fitPX(16) },
    lh17: { lineHeight: fitPX(17) },
    lh18: { lineHeight: fitPX(18) },
    lh19: { lineHeight: fitPX(19) },
    lh20: { lineHeight: fitPX(20) },
    lh21: { lineHeight: fitPX(21) },
    lh22: { lineHeight: fitPX(22) },
    lh23: { lineHeight: fitPX(23) },
    lh24: { lineHeight: fitPX(24) },
    lh25: { lineHeight: fitPX(25) },
    lh26: { lineHeight: fitPX(26) },
    lh27: { lineHeight: fitPX(27) },
    lh28: { lineHeight: fitPX(28) },
    lh29: { lineHeight: fitPX(29) },
    lh30: { lineHeight: fitPX(30) },

    lh_0: { lineHeight: fitPX(-0) },
    lh_1: { lineHeight: fitPX(-1) },
    lh_2: { lineHeight: fitPX(-2) },
    lh_3: { lineHeight: fitPX(-3) },
    lh_4: { lineHeight: fitPX(-4) },
    lh_5: { lineHeight: fitPX(-5) },
    lh_6: { lineHeight: fitPX(-6) },
    lh_7: { lineHeight: fitPX(-7) },
    lh_8: { lineHeight: fitPX(-8) },
    lh_9: { lineHeight: fitPX(-9) },
    lh_10: { lineHeight: fitPX(-10) },
    lh_11: { lineHeight: fitPX(-11) },
    lh_12: { lineHeight: fitPX(-12) },
    lh_13: { lineHeight: fitPX(-13) },
    lh_14: { lineHeight: fitPX(-14) },
    lh_15: { lineHeight: fitPX(-15) },
    lh_16: { lineHeight: fitPX(-16) },
    lh_17: { lineHeight: fitPX(-17) },
    lh_18: { lineHeight: fitPX(-18) },
    lh_19: { lineHeight: fitPX(-19) },
    lh_20: { lineHeight: fitPX(-20) },
    lh_21: { lineHeight: fitPX(-21) },
    lh_22: { lineHeight: fitPX(-22) },
    lh_23: { lineHeight: fitPX(-23) },
    lh_24: { lineHeight: fitPX(-24) },
    lh_25: { lineHeight: fitPX(-25) },
    lh_26: { lineHeight: fitPX(-26) },
    lh_27: { lineHeight: fitPX(-27) },
    lh_28: { lineHeight: fitPX(-28) },
    lh_29: { lineHeight: fitPX(-29) },
    lh_30: { lineHeight: fitPX(-30) },

    m: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            marginHorizontal: fitPX(number), marginVertical: fitPX(number)
        }
    },
    m0: { marginHorizontal: fitPX(0), marginVertical: fitPX(0) },
    m1: { marginHorizontal: fitPX(1), marginVertical: fitPX(1) },
    m2: { marginHorizontal: fitPX(2), marginVertical: fitPX(2) },
    m3: { marginHorizontal: fitPX(3), marginVertical: fitPX(3) },
    m4: { marginHorizontal: fitPX(4), marginVertical: fitPX(4) },
    m5: { marginHorizontal: fitPX(5), marginVertical: fitPX(5) },
    m6: { marginHorizontal: fitPX(6), marginVertical: fitPX(6) },
    m7: { marginHorizontal: fitPX(7), marginVertical: fitPX(7) },
    m8: { marginHorizontal: fitPX(8), marginVertical: fitPX(8) },
    m9: { marginHorizontal: fitPX(9), marginVertical: fitPX(9) },
    m10: { marginHorizontal: fitPX(10), marginVertical: fitPX(10) },
    m11: { marginHorizontal: fitPX(11), marginVertical: fitPX(11) },
    m12: { marginHorizontal: fitPX(12), marginVertical: fitPX(12) },
    m13: { marginHorizontal: fitPX(13), marginVertical: fitPX(13) },
    m14: { marginHorizontal: fitPX(14), marginVertical: fitPX(14) },
    m15: { marginHorizontal: fitPX(15), marginVertical: fitPX(15) },
    m16: { marginHorizontal: fitPX(16), marginVertical: fitPX(16) },
    m17: { marginHorizontal: fitPX(17), marginVertical: fitPX(17) },
    m18: { marginHorizontal: fitPX(18), marginVertical: fitPX(18) },
    m19: { marginHorizontal: fitPX(19), marginVertical: fitPX(19) },
    m20: { marginHorizontal: fitPX(20), marginVertical: fitPX(20) },
    m21: { marginHorizontal: fitPX(21), marginVertical: fitPX(21) },
    m22: { marginHorizontal: fitPX(22), marginVertical: fitPX(22) },
    m23: { marginHorizontal: fitPX(23), marginVertical: fitPX(23) },
    m24: { marginHorizontal: fitPX(24), marginVertical: fitPX(24) },
    m25: { marginHorizontal: fitPX(25), marginVertical: fitPX(25) },
    m26: { marginHorizontal: fitPX(26), marginVertical: fitPX(26) },
    m27: { marginHorizontal: fitPX(27), marginVertical: fitPX(27) },
    m28: { marginHorizontal: fitPX(28), marginVertical: fitPX(28) },
    m29: { marginHorizontal: fitPX(29), marginVertical: fitPX(29) },
    m30: { marginHorizontal: fitPX(30), marginVertical: fitPX(30) },

    m_0: { marginHorizontal: fitPX(-0), marginVertical: fitPX(-0) },
    m_1: { marginHorizontal: fitPX(-1), marginVertical: fitPX(-1) },
    m_2: { marginHorizontal: fitPX(-2), marginVertical: fitPX(-2) },
    m_3: { marginHorizontal: fitPX(-3), marginVertical: fitPX(-3) },
    m_4: { marginHorizontal: fitPX(-4), marginVertical: fitPX(-4) },
    m_5: { marginHorizontal: fitPX(-5), marginVertical: fitPX(-5) },
    m_6: { marginHorizontal: fitPX(-6), marginVertical: fitPX(-6) },
    m_7: { marginHorizontal: fitPX(-7), marginVertical: fitPX(-7) },
    m_8: { marginHorizontal: fitPX(-8), marginVertical: fitPX(-8) },
    m_9: { marginHorizontal: fitPX(-9), marginVertical: fitPX(-9) },
    m_10: { marginHorizontal: fitPX(-10), marginVertical: fitPX(-10) },
    m_11: { marginHorizontal: fitPX(-11), marginVertical: fitPX(-11) },
    m_12: { marginHorizontal: fitPX(-12), marginVertical: fitPX(-12) },
    m_13: { marginHorizontal: fitPX(-13), marginVertical: fitPX(-13) },
    m_14: { marginHorizontal: fitPX(-14), marginVertical: fitPX(-14) },
    m_15: { marginHorizontal: fitPX(-15), marginVertical: fitPX(-15) },
    m_16: { marginHorizontal: fitPX(-16), marginVertical: fitPX(-16) },
    m_17: { marginHorizontal: fitPX(-17), marginVertical: fitPX(-17) },
    m_18: { marginHorizontal: fitPX(-18), marginVertical: fitPX(-18) },
    m_19: { marginHorizontal: fitPX(-19), marginVertical: fitPX(-19) },
    m_20: { marginHorizontal: fitPX(-20), marginVertical: fitPX(-20) },
    m_21: { marginHorizontal: fitPX(-21), marginVertical: fitPX(-21) },
    m_22: { marginHorizontal: fitPX(-22), marginVertical: fitPX(-22) },
    m_23: { marginHorizontal: fitPX(-23), marginVertical: fitPX(-23) },
    m_24: { marginHorizontal: fitPX(-24), marginVertical: fitPX(-24) },
    m_25: { marginHorizontal: fitPX(-25), marginVertical: fitPX(-25) },
    m_26: { marginHorizontal: fitPX(-26), marginVertical: fitPX(-26) },
    m_27: { marginHorizontal: fitPX(-27), marginVertical: fitPX(-27) },
    m_28: { marginHorizontal: fitPX(-28), marginVertical: fitPX(-28) },
    m_29: { marginHorizontal: fitPX(-29), marginVertical: fitPX(-29) },
    m_30: { marginHorizontal: fitPX(-30), marginVertical: fitPX(-30) },


    mh: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            marginHorizontal: fitPX(number)
        }
    },
    mh0: { marginHorizontal: fitPX(0) },
    mh1: { marginHorizontal: fitPX(1) },
    mh2: { marginHorizontal: fitPX(2) },
    mh3: { marginHorizontal: fitPX(3) },
    mh4: { marginHorizontal: fitPX(4) },
    mh5: { marginHorizontal: fitPX(5) },
    mh6: { marginHorizontal: fitPX(6) },
    mh7: { marginHorizontal: fitPX(7) },
    mh8: { marginHorizontal: fitPX(8) },
    mh9: { marginHorizontal: fitPX(9) },
    mh10: { marginHorizontal: fitPX(10) },
    mh11: { marginHorizontal: fitPX(11) },
    mh12: { marginHorizontal: fitPX(12) },
    mh13: { marginHorizontal: fitPX(13) },
    mh14: { marginHorizontal: fitPX(14) },
    mh15: { marginHorizontal: fitPX(15) },
    mh16: { marginHorizontal: fitPX(16) },
    mh17: { marginHorizontal: fitPX(17) },
    mh18: { marginHorizontal: fitPX(18) },
    mh19: { marginHorizontal: fitPX(19) },
    mh20: { marginHorizontal: fitPX(20) },
    mh21: { marginHorizontal: fitPX(21) },
    mh22: { marginHorizontal: fitPX(22) },
    mh23: { marginHorizontal: fitPX(23) },
    mh24: { marginHorizontal: fitPX(24) },
    mh25: { marginHorizontal: fitPX(25) },
    mh26: { marginHorizontal: fitPX(26) },
    mh27: { marginHorizontal: fitPX(27) },
    mh28: { marginHorizontal: fitPX(28) },
    mh29: { marginHorizontal: fitPX(29) },
    mh30: { marginHorizontal: fitPX(30) },

    mh_0: { marginHorizontal: fitPX(-0) },
    mh_1: { marginHorizontal: fitPX(-1) },
    mh_2: { marginHorizontal: fitPX(-2) },
    mh_3: { marginHorizontal: fitPX(-3) },
    mh_4: { marginHorizontal: fitPX(-4) },
    mh_5: { marginHorizontal: fitPX(-5) },
    mh_6: { marginHorizontal: fitPX(-6) },
    mh_7: { marginHorizontal: fitPX(-7) },
    mh_8: { marginHorizontal: fitPX(-8) },
    mh_9: { marginHorizontal: fitPX(-9) },
    mh_10: { marginHorizontal: fitPX(-10) },
    mh_11: { marginHorizontal: fitPX(-11) },
    mh_12: { marginHorizontal: fitPX(-12) },
    mh_13: { marginHorizontal: fitPX(-13) },
    mh_14: { marginHorizontal: fitPX(-14) },
    mh_15: { marginHorizontal: fitPX(-15) },
    mh_16: { marginHorizontal: fitPX(-16) },
    mh_17: { marginHorizontal: fitPX(-17) },
    mh_18: { marginHorizontal: fitPX(-18) },
    mh_19: { marginHorizontal: fitPX(-19) },
    mh_20: { marginHorizontal: fitPX(-20) },
    mh_21: { marginHorizontal: fitPX(-21) },
    mh_22: { marginHorizontal: fitPX(-22) },
    mh_23: { marginHorizontal: fitPX(-23) },
    mh_24: { marginHorizontal: fitPX(-24) },
    mh_25: { marginHorizontal: fitPX(-25) },
    mh_26: { marginHorizontal: fitPX(-26) },
    mh_27: { marginHorizontal: fitPX(-27) },
    mh_28: { marginHorizontal: fitPX(-28) },
    mh_29: { marginHorizontal: fitPX(-29) },
    mh_30: { marginHorizontal: fitPX(-30) },

    mv: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            marginVertical: fitPX(number)
        }
    },
    mv0: { marginVertical: fitPX(0) },
    mv1: { marginVertical: fitPX(1) },
    mv2: { marginVertical: fitPX(2) },
    mv3: { marginVertical: fitPX(3) },
    mv4: { marginVertical: fitPX(4) },
    mv5: { marginVertical: fitPX(5) },
    mv6: { marginVertical: fitPX(6) },
    mv7: { marginVertical: fitPX(7) },
    mv8: { marginVertical: fitPX(8) },
    mv9: { marginVertical: fitPX(9) },
    mv10: { marginVertical: fitPX(10) },
    mv11: { marginVertical: fitPX(11) },
    mv12: { marginVertical: fitPX(12) },
    mv13: { marginVertical: fitPX(13) },
    mv14: { marginVertical: fitPX(14) },
    mv15: { marginVertical: fitPX(15) },
    mv16: { marginVertical: fitPX(16) },
    mv17: { marginVertical: fitPX(17) },
    mv18: { marginVertical: fitPX(18) },
    mv19: { marginVertical: fitPX(19) },
    mv20: { marginVertical: fitPX(20) },
    mv21: { marginVertical: fitPX(21) },
    mv22: { marginVertical: fitPX(22) },
    mv23: { marginVertical: fitPX(23) },
    mv24: { marginVertical: fitPX(24) },
    mv25: { marginVertical: fitPX(25) },
    mv26: { marginVertical: fitPX(26) },
    mv27: { marginVertical: fitPX(27) },
    mv28: { marginVertical: fitPX(28) },
    mv29: { marginVertical: fitPX(29) },
    mv30: { marginVertical: fitPX(30) },

    mv_0: { marginVertical: fitPX(-0) },
    mv_1: { marginVertical: fitPX(-1) },
    mv_2: { marginVertical: fitPX(-2) },
    mv_3: { marginVertical: fitPX(-3) },
    mv_4: { marginVertical: fitPX(-4) },
    mv_5: { marginVertical: fitPX(-5) },
    mv_6: { marginVertical: fitPX(-6) },
    mv_7: { marginVertical: fitPX(-7) },
    mv_8: { marginVertical: fitPX(-8) },
    mv_9: { marginVertical: fitPX(-9) },
    mv_10: { marginVertical: fitPX(-10) },
    mv_11: { marginVertical: fitPX(-11) },
    mv_12: { marginVertical: fitPX(-12) },
    mv_13: { marginVertical: fitPX(-13) },
    mv_14: { marginVertical: fitPX(-14) },
    mv_15: { marginVertical: fitPX(-15) },
    mv_16: { marginVertical: fitPX(-16) },
    mv_17: { marginVertical: fitPX(-17) },
    mv_18: { marginVertical: fitPX(-18) },
    mv_19: { marginVertical: fitPX(-19) },
    mv_20: { marginVertical: fitPX(-20) },
    mv_21: { marginVertical: fitPX(-21) },
    mv_22: { marginVertical: fitPX(-22) },
    mv_23: { marginVertical: fitPX(-23) },
    mv_24: { marginVertical: fitPX(-24) },
    mv_25: { marginVertical: fitPX(-25) },
    mv_26: { marginVertical: fitPX(-26) },
    mv_27: { marginVertical: fitPX(-27) },
    mv_28: { marginVertical: fitPX(-28) },
    mv_29: { marginVertical: fitPX(-29) },
    mv_30: { marginVertical: fitPX(-30) },

    mt: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            marginTop: fitPX(number)
        }
    },
    mt0: { marginTop: fitPX(0) },
    mt1: { marginTop: fitPX(1) },
    mt2: { marginTop: fitPX(2) },
    mt3: { marginTop: fitPX(3) },
    mt4: { marginTop: fitPX(4) },
    mt5: { marginTop: fitPX(5) },
    mt6: { marginTop: fitPX(6) },
    mt7: { marginTop: fitPX(7) },
    mt8: { marginTop: fitPX(8) },
    mt9: { marginTop: fitPX(9) },
    mt10: { marginTop: fitPX(10) },
    mt11: { marginTop: fitPX(11) },
    mt12: { marginTop: fitPX(12) },
    mt13: { marginTop: fitPX(13) },
    mt14: { marginTop: fitPX(14) },
    mt15: { marginTop: fitPX(15) },
    mt16: { marginTop: fitPX(16) },
    mt17: { marginTop: fitPX(17) },
    mt18: { marginTop: fitPX(18) },
    mt19: { marginTop: fitPX(19) },
    mt20: { marginTop: fitPX(20) },
    mt21: { marginTop: fitPX(21) },
    mt22: { marginTop: fitPX(22) },
    mt23: { marginTop: fitPX(23) },
    mt24: { marginTop: fitPX(24) },
    mt25: { marginTop: fitPX(25) },
    mt26: { marginTop: fitPX(26) },
    mt27: { marginTop: fitPX(27) },
    mt28: { marginTop: fitPX(28) },
    mt29: { marginTop: fitPX(29) },
    mt30: { marginTop: fitPX(30) },

    mt_0: { marginTop: fitPX(-0) },
    mt_1: { marginTop: fitPX(-1) },
    mt_2: { marginTop: fitPX(-2) },
    mt_3: { marginTop: fitPX(-3) },
    mt_4: { marginTop: fitPX(-4) },
    mt_5: { marginTop: fitPX(-5) },
    mt_6: { marginTop: fitPX(-6) },
    mt_7: { marginTop: fitPX(-7) },
    mt_8: { marginTop: fitPX(-8) },
    mt_9: { marginTop: fitPX(-9) },
    mt_10: { marginTop: fitPX(-10) },
    mt_11: { marginTop: fitPX(-11) },
    mt_12: { marginTop: fitPX(-12) },
    mt_13: { marginTop: fitPX(-13) },
    mt_14: { marginTop: fitPX(-14) },
    mt_15: { marginTop: fitPX(-15) },
    mt_16: { marginTop: fitPX(-16) },
    mt_17: { marginTop: fitPX(-17) },
    mt_18: { marginTop: fitPX(-18) },
    mt_19: { marginTop: fitPX(-19) },
    mt_20: { marginTop: fitPX(-20) },
    mt_21: { marginTop: fitPX(-21) },
    mt_22: { marginTop: fitPX(-22) },
    mt_23: { marginTop: fitPX(-23) },
    mt_24: { marginTop: fitPX(-24) },
    mt_25: { marginTop: fitPX(-25) },
    mt_26: { marginTop: fitPX(-26) },
    mt_27: { marginTop: fitPX(-27) },
    mt_28: { marginTop: fitPX(-28) },
    mt_29: { marginTop: fitPX(-29) },
    mt_30: { marginTop: fitPX(-30) },

    mr: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            marginRight: fitPX(number)
        }
    },
    mr0: { marginRight: fitPX(0) },
    mr1: { marginRight: fitPX(1) },
    mr2: { marginRight: fitPX(2) },
    mr3: { marginRight: fitPX(3) },
    mr4: { marginRight: fitPX(4) },
    mr5: { marginRight: fitPX(5) },
    mr6: { marginRight: fitPX(6) },
    mr7: { marginRight: fitPX(7) },
    mr8: { marginRight: fitPX(8) },
    mr9: { marginRight: fitPX(9) },
    mr10: { marginRight: fitPX(10) },
    mr11: { marginRight: fitPX(11) },
    mr12: { marginRight: fitPX(12) },
    mr13: { marginRight: fitPX(13) },
    mr14: { marginRight: fitPX(14) },
    mr15: { marginRight: fitPX(15) },
    mr16: { marginRight: fitPX(16) },
    mr17: { marginRight: fitPX(17) },
    mr18: { marginRight: fitPX(18) },
    mr19: { marginRight: fitPX(19) },
    mr20: { marginRight: fitPX(20) },
    mr21: { marginRight: fitPX(21) },
    mr22: { marginRight: fitPX(22) },
    mr23: { marginRight: fitPX(23) },
    mr24: { marginRight: fitPX(24) },
    mr25: { marginRight: fitPX(25) },
    mr26: { marginRight: fitPX(26) },
    mr27: { marginRight: fitPX(27) },
    mr28: { marginRight: fitPX(28) },
    mr29: { marginRight: fitPX(29) },
    mr30: { marginRight: fitPX(30) },

    mr_0: { marginRight: fitPX(-0) },
    mr_1: { marginRight: fitPX(-1) },
    mr_2: { marginRight: fitPX(-2) },
    mr_3: { marginRight: fitPX(-3) },
    mr_4: { marginRight: fitPX(-4) },
    mr_5: { marginRight: fitPX(-5) },
    mr_6: { marginRight: fitPX(-6) },
    mr_7: { marginRight: fitPX(-7) },
    mr_8: { marginRight: fitPX(-8) },
    mr_9: { marginRight: fitPX(-9) },
    mr_10: { marginRight: fitPX(-10) },
    mr_11: { marginRight: fitPX(-11) },
    mr_12: { marginRight: fitPX(-12) },
    mr_13: { marginRight: fitPX(-13) },
    mr_14: { marginRight: fitPX(-14) },
    mr_15: { marginRight: fitPX(-15) },
    mr_16: { marginRight: fitPX(-16) },
    mr_17: { marginRight: fitPX(-17) },
    mr_18: { marginRight: fitPX(-18) },
    mr_19: { marginRight: fitPX(-19) },
    mr_20: { marginRight: fitPX(-20) },
    mr_21: { marginRight: fitPX(-21) },
    mr_22: { marginRight: fitPX(-22) },
    mr_23: { marginRight: fitPX(-23) },
    mr_24: { marginRight: fitPX(-24) },
    mr_25: { marginRight: fitPX(-25) },
    mr_26: { marginRight: fitPX(-26) },
    mr_27: { marginRight: fitPX(-27) },
    mr_28: { marginRight: fitPX(-28) },
    mr_29: { marginRight: fitPX(-29) },
    mr_30: { marginRight: fitPX(-30) },

    mb: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            marginBottom: fitPX(number)
        }
    },
    mb0: { marginBottom: fitPX(0) },
    mb1: { marginBottom: fitPX(1) },
    mb2: { marginBottom: fitPX(2) },
    mb3: { marginBottom: fitPX(3) },
    mb4: { marginBottom: fitPX(4) },
    mb5: { marginBottom: fitPX(5) },
    mb6: { marginBottom: fitPX(6) },
    mb7: { marginBottom: fitPX(7) },
    mb8: { marginBottom: fitPX(8) },
    mb9: { marginBottom: fitPX(9) },
    mb10: { marginBottom: fitPX(10) },
    mb11: { marginBottom: fitPX(11) },
    mb12: { marginBottom: fitPX(12) },
    mb13: { marginBottom: fitPX(13) },
    mb14: { marginBottom: fitPX(14) },
    mb15: { marginBottom: fitPX(15) },
    mb16: { marginBottom: fitPX(16) },
    mb17: { marginBottom: fitPX(17) },
    mb18: { marginBottom: fitPX(18) },
    mb19: { marginBottom: fitPX(19) },
    mb20: { marginBottom: fitPX(20) },
    mb21: { marginBottom: fitPX(21) },
    mb22: { marginBottom: fitPX(22) },
    mb23: { marginBottom: fitPX(23) },
    mb24: { marginBottom: fitPX(24) },
    mb25: { marginBottom: fitPX(25) },
    mb26: { marginBottom: fitPX(26) },
    mb27: { marginBottom: fitPX(27) },
    mb28: { marginBottom: fitPX(28) },
    mb29: { marginBottom: fitPX(29) },
    mb30: { marginBottom: fitPX(30) },

    mb_0: { marginBottom: fitPX(-0) },
    mb_1: { marginBottom: fitPX(-1) },
    mb_2: { marginBottom: fitPX(-2) },
    mb_3: { marginBottom: fitPX(-3) },
    mb_4: { marginBottom: fitPX(-4) },
    mb_5: { marginBottom: fitPX(-5) },
    mb_6: { marginBottom: fitPX(-6) },
    mb_7: { marginBottom: fitPX(-7) },
    mb_8: { marginBottom: fitPX(-8) },
    mb_9: { marginBottom: fitPX(-9) },
    mb_10: { marginBottom: fitPX(-10) },
    mb_11: { marginBottom: fitPX(-11) },
    mb_12: { marginBottom: fitPX(-12) },
    mb_13: { marginBottom: fitPX(-13) },
    mb_14: { marginBottom: fitPX(-14) },
    mb_15: { marginBottom: fitPX(-15) },
    mb_16: { marginBottom: fitPX(-16) },
    mb_17: { marginBottom: fitPX(-17) },
    mb_18: { marginBottom: fitPX(-18) },
    mb_19: { marginBottom: fitPX(-19) },
    mb_20: { marginBottom: fitPX(-20) },
    mb_21: { marginBottom: fitPX(-21) },
    mb_22: { marginBottom: fitPX(-22) },
    mb_23: { marginBottom: fitPX(-23) },
    mb_24: { marginBottom: fitPX(-24) },
    mb_25: { marginBottom: fitPX(-25) },
    mb_26: { marginBottom: fitPX(-26) },
    mb_27: { marginBottom: fitPX(-27) },
    mb_28: { marginBottom: fitPX(-28) },
    mb_29: { marginBottom: fitPX(-29) },
    mb_30: { marginBottom: fitPX(-30) },

    ml: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            marginLeft: fitPX(number)
        }
    },
    ml0: { marginLeft: fitPX(0) },
    ml1: { marginLeft: fitPX(1) },
    ml2: { marginLeft: fitPX(2) },
    ml3: { marginLeft: fitPX(3) },
    ml4: { marginLeft: fitPX(4) },
    ml5: { marginLeft: fitPX(5) },
    ml6: { marginLeft: fitPX(6) },
    ml7: { marginLeft: fitPX(7) },
    ml8: { marginLeft: fitPX(8) },
    ml9: { marginLeft: fitPX(9) },
    ml10: { marginLeft: fitPX(10) },
    ml11: { marginLeft: fitPX(11) },
    ml12: { marginLeft: fitPX(12) },
    ml13: { marginLeft: fitPX(13) },
    ml14: { marginLeft: fitPX(14) },
    ml15: { marginLeft: fitPX(15) },
    ml16: { marginLeft: fitPX(16) },
    ml17: { marginLeft: fitPX(17) },
    ml18: { marginLeft: fitPX(18) },
    ml19: { marginLeft: fitPX(19) },
    ml20: { marginLeft: fitPX(20) },
    ml21: { marginLeft: fitPX(21) },
    ml22: { marginLeft: fitPX(22) },
    ml23: { marginLeft: fitPX(23) },
    ml24: { marginLeft: fitPX(24) },
    ml25: { marginLeft: fitPX(25) },
    ml26: { marginLeft: fitPX(26) },
    ml27: { marginLeft: fitPX(27) },
    ml28: { marginLeft: fitPX(28) },
    ml29: { marginLeft: fitPX(29) },
    ml30: { marginLeft: fitPX(30) },

    ml_0: { marginLeft: fitPX(-0) },
    ml_1: { marginLeft: fitPX(-1) },
    ml_2: { marginLeft: fitPX(-2) },
    ml_3: { marginLeft: fitPX(-3) },
    ml_4: { marginLeft: fitPX(-4) },
    ml_5: { marginLeft: fitPX(-5) },
    ml_6: { marginLeft: fitPX(-6) },
    ml_7: { marginLeft: fitPX(-7) },
    ml_8: { marginLeft: fitPX(-8) },
    ml_9: { marginLeft: fitPX(-9) },
    ml_10: { marginLeft: fitPX(-10) },
    ml_11: { marginLeft: fitPX(-11) },
    ml_12: { marginLeft: fitPX(-12) },
    ml_13: { marginLeft: fitPX(-13) },
    ml_14: { marginLeft: fitPX(-14) },
    ml_15: { marginLeft: fitPX(-15) },
    ml_16: { marginLeft: fitPX(-16) },
    ml_17: { marginLeft: fitPX(-17) },
    ml_18: { marginLeft: fitPX(-18) },
    ml_19: { marginLeft: fitPX(-19) },
    ml_20: { marginLeft: fitPX(-20) },
    ml_21: { marginLeft: fitPX(-21) },
    ml_22: { marginLeft: fitPX(-22) },
    ml_23: { marginLeft: fitPX(-23) },
    ml_24: { marginLeft: fitPX(-24) },
    ml_25: { marginLeft: fitPX(-25) },
    ml_26: { marginLeft: fitPX(-26) },
    ml_27: { marginLeft: fitPX(-27) },
    ml_28: { marginLeft: fitPX(-28) },
    ml_29: { marginLeft: fitPX(-29) },
    ml_30: { marginLeft: fitPX(-30) },

    p: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            paddingHorizontal: fitPX(number), paddingVertical: fitPX(number)
        }
    },
    p0: { paddingHorizontal: fitPX(0), paddingVertical: fitPX(0) },
    p1: { paddingHorizontal: fitPX(1), paddingVertical: fitPX(1) },
    p2: { paddingHorizontal: fitPX(2), paddingVertical: fitPX(2) },
    p3: { paddingHorizontal: fitPX(3), paddingVertical: fitPX(3) },
    p4: { paddingHorizontal: fitPX(4), paddingVertical: fitPX(4) },
    p5: { paddingHorizontal: fitPX(5), paddingVertical: fitPX(5) },
    p6: { paddingHorizontal: fitPX(6), paddingVertical: fitPX(6) },
    p7: { paddingHorizontal: fitPX(7), paddingVertical: fitPX(7) },
    p8: { paddingHorizontal: fitPX(8), paddingVertical: fitPX(8) },
    p9: { paddingHorizontal: fitPX(9), paddingVertical: fitPX(9) },
    p10: { paddingHorizontal: fitPX(10), paddingVertical: fitPX(10) },
    p11: { paddingHorizontal: fitPX(11), paddingVertical: fitPX(11) },
    p12: { paddingHorizontal: fitPX(12), paddingVertical: fitPX(12) },
    p13: { paddingHorizontal: fitPX(13), paddingVertical: fitPX(13) },
    p14: { paddingHorizontal: fitPX(14), paddingVertical: fitPX(14) },
    p15: { paddingHorizontal: fitPX(15), paddingVertical: fitPX(15) },
    p16: { paddingHorizontal: fitPX(16), paddingVertical: fitPX(16) },
    p17: { paddingHorizontal: fitPX(17), paddingVertical: fitPX(17) },
    p18: { paddingHorizontal: fitPX(18), paddingVertical: fitPX(18) },
    p19: { paddingHorizontal: fitPX(19), paddingVertical: fitPX(19) },
    p20: { paddingHorizontal: fitPX(20), paddingVertical: fitPX(20) },
    p21: { paddingHorizontal: fitPX(21), paddingVertical: fitPX(21) },
    p22: { paddingHorizontal: fitPX(22), paddingVertical: fitPX(22) },
    p23: { paddingHorizontal: fitPX(23), paddingVertical: fitPX(23) },
    p24: { paddingHorizontal: fitPX(24), paddingVertical: fitPX(24) },
    p25: { paddingHorizontal: fitPX(25), paddingVertical: fitPX(25) },
    p26: { paddingHorizontal: fitPX(26), paddingVertical: fitPX(26) },
    p27: { paddingHorizontal: fitPX(27), paddingVertical: fitPX(27) },
    p28: { paddingHorizontal: fitPX(28), paddingVertical: fitPX(28) },
    p29: { paddingHorizontal: fitPX(29), paddingVertical: fitPX(29) },
    p30: { paddingHorizontal: fitPX(30), paddingVertical: fitPX(30) },

    p_0: { paddingHorizontal: fitPX(-0), paddingVertical: fitPX(-0) },
    p_1: { paddingHorizontal: fitPX(-1), paddingVertical: fitPX(-1) },
    p_2: { paddingHorizontal: fitPX(-2), paddingVertical: fitPX(-2) },
    p_3: { paddingHorizontal: fitPX(-3), paddingVertical: fitPX(-3) },
    p_4: { paddingHorizontal: fitPX(-4), paddingVertical: fitPX(-4) },
    p_5: { paddingHorizontal: fitPX(-5), paddingVertical: fitPX(-5) },
    p_6: { paddingHorizontal: fitPX(-6), paddingVertical: fitPX(-6) },
    p_7: { paddingHorizontal: fitPX(-7), paddingVertical: fitPX(-7) },
    p_8: { paddingHorizontal: fitPX(-8), paddingVertical: fitPX(-8) },
    p_9: { paddingHorizontal: fitPX(-9), paddingVertical: fitPX(-9) },
    p_10: { paddingHorizontal: fitPX(-10), paddingVertical: fitPX(-10) },
    p_11: { paddingHorizontal: fitPX(-11), paddingVertical: fitPX(-11) },
    p_12: { paddingHorizontal: fitPX(-12), paddingVertical: fitPX(-12) },
    p_13: { paddingHorizontal: fitPX(-13), paddingVertical: fitPX(-13) },
    p_14: { paddingHorizontal: fitPX(-14), paddingVertical: fitPX(-14) },
    p_15: { paddingHorizontal: fitPX(-15), paddingVertical: fitPX(-15) },
    p_16: { paddingHorizontal: fitPX(-16), paddingVertical: fitPX(-16) },
    p_17: { paddingHorizontal: fitPX(-17), paddingVertical: fitPX(-17) },
    p_18: { paddingHorizontal: fitPX(-18), paddingVertical: fitPX(-18) },
    p_19: { paddingHorizontal: fitPX(-19), paddingVertical: fitPX(-19) },
    p_20: { paddingHorizontal: fitPX(-20), paddingVertical: fitPX(-20) },
    p_21: { paddingHorizontal: fitPX(-21), paddingVertical: fitPX(-21) },
    p_22: { paddingHorizontal: fitPX(-22), paddingVertical: fitPX(-22) },
    p_23: { paddingHorizontal: fitPX(-23), paddingVertical: fitPX(-23) },
    p_24: { paddingHorizontal: fitPX(-24), paddingVertical: fitPX(-24) },
    p_25: { paddingHorizontal: fitPX(-25), paddingVertical: fitPX(-25) },
    p_26: { paddingHorizontal: fitPX(-26), paddingVertical: fitPX(-26) },
    p_27: { paddingHorizontal: fitPX(-27), paddingVertical: fitPX(-27) },
    p_28: { paddingHorizontal: fitPX(-28), paddingVertical: fitPX(-28) },
    p_29: { paddingHorizontal: fitPX(-29), paddingVertical: fitPX(-29) },
    p_30: { paddingHorizontal: fitPX(-30), paddingVertical: fitPX(-30) },

    ph: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            paddingHorizontal: fitPX(number)
        }
    },
    ph0: { paddingHorizontal: fitPX(0) },
    ph1: { paddingHorizontal: fitPX(1) },
    ph2: { paddingHorizontal: fitPX(2) },
    ph3: { paddingHorizontal: fitPX(3) },
    ph4: { paddingHorizontal: fitPX(4) },
    ph5: { paddingHorizontal: fitPX(5) },
    ph6: { paddingHorizontal: fitPX(6) },
    ph7: { paddingHorizontal: fitPX(7) },
    ph8: { paddingHorizontal: fitPX(8) },
    ph9: { paddingHorizontal: fitPX(9) },
    ph10: { paddingHorizontal: fitPX(10) },
    ph11: { paddingHorizontal: fitPX(11) },
    ph12: { paddingHorizontal: fitPX(12) },
    ph13: { paddingHorizontal: fitPX(13) },
    ph14: { paddingHorizontal: fitPX(14) },
    ph15: { paddingHorizontal: fitPX(15) },
    ph16: { paddingHorizontal: fitPX(16) },
    ph17: { paddingHorizontal: fitPX(17) },
    ph18: { paddingHorizontal: fitPX(18) },
    ph19: { paddingHorizontal: fitPX(19) },
    ph20: { paddingHorizontal: fitPX(20) },
    ph21: { paddingHorizontal: fitPX(21) },
    ph22: { paddingHorizontal: fitPX(22) },
    ph23: { paddingHorizontal: fitPX(23) },
    ph24: { paddingHorizontal: fitPX(24) },
    ph25: { paddingHorizontal: fitPX(25) },
    ph26: { paddingHorizontal: fitPX(26) },
    ph27: { paddingHorizontal: fitPX(27) },
    ph28: { paddingHorizontal: fitPX(28) },
    ph29: { paddingHorizontal: fitPX(29) },
    ph30: { paddingHorizontal: fitPX(30) },

    ph_0: { paddingHorizontal: fitPX(-0) },
    ph_1: { paddingHorizontal: fitPX(-1) },
    ph_2: { paddingHorizontal: fitPX(-2) },
    ph_3: { paddingHorizontal: fitPX(-3) },
    ph_4: { paddingHorizontal: fitPX(-4) },
    ph_5: { paddingHorizontal: fitPX(-5) },
    ph_6: { paddingHorizontal: fitPX(-6) },
    ph_7: { paddingHorizontal: fitPX(-7) },
    ph_8: { paddingHorizontal: fitPX(-8) },
    ph_9: { paddingHorizontal: fitPX(-9) },
    ph_10: { paddingHorizontal: fitPX(-10) },
    ph_11: { paddingHorizontal: fitPX(-11) },
    ph_12: { paddingHorizontal: fitPX(-12) },
    ph_13: { paddingHorizontal: fitPX(-13) },
    ph_14: { paddingHorizontal: fitPX(-14) },
    ph_15: { paddingHorizontal: fitPX(-15) },
    ph_16: { paddingHorizontal: fitPX(-16) },
    ph_17: { paddingHorizontal: fitPX(-17) },
    ph_18: { paddingHorizontal: fitPX(-18) },
    ph_19: { paddingHorizontal: fitPX(-19) },
    ph_20: { paddingHorizontal: fitPX(-20) },
    ph_21: { paddingHorizontal: fitPX(-21) },
    ph_22: { paddingHorizontal: fitPX(-22) },
    ph_23: { paddingHorizontal: fitPX(-23) },
    ph_24: { paddingHorizontal: fitPX(-24) },
    ph_25: { paddingHorizontal: fitPX(-25) },
    ph_26: { paddingHorizontal: fitPX(-26) },
    ph_27: { paddingHorizontal: fitPX(-27) },
    ph_28: { paddingHorizontal: fitPX(-28) },
    ph_29: { paddingHorizontal: fitPX(-29) },
    ph_30: { paddingHorizontal: fitPX(-30) },

    pv: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            paddingVertical: fitPX(number)
        }
    },
    pv0: { paddingVertical: fitPX(0) },
    pv1: { paddingVertical: fitPX(1) },
    pv2: { paddingVertical: fitPX(2) },
    pv3: { paddingVertical: fitPX(3) },
    pv4: { paddingVertical: fitPX(4) },
    pv5: { paddingVertical: fitPX(5) },
    pv6: { paddingVertical: fitPX(6) },
    pv7: { paddingVertical: fitPX(7) },
    pv8: { paddingVertical: fitPX(8) },
    pv9: { paddingVertical: fitPX(9) },
    pv10: { paddingVertical: fitPX(10) },
    pv11: { paddingVertical: fitPX(11) },
    pv12: { paddingVertical: fitPX(12) },
    pv13: { paddingVertical: fitPX(13) },
    pv14: { paddingVertical: fitPX(14) },
    pv15: { paddingVertical: fitPX(15) },
    pv16: { paddingVertical: fitPX(16) },
    pv17: { paddingVertical: fitPX(17) },
    pv18: { paddingVertical: fitPX(18) },
    pv19: { paddingVertical: fitPX(19) },
    pv20: { paddingVertical: fitPX(20) },
    pv21: { paddingVertical: fitPX(21) },
    pv22: { paddingVertical: fitPX(22) },
    pv23: { paddingVertical: fitPX(23) },
    pv24: { paddingVertical: fitPX(24) },
    pv25: { paddingVertical: fitPX(25) },
    pv26: { paddingVertical: fitPX(26) },
    pv27: { paddingVertical: fitPX(27) },
    pv28: { paddingVertical: fitPX(28) },
    pv29: { paddingVertical: fitPX(29) },
    pv30: { paddingVertical: fitPX(30) },

    pv_0: { paddingVertical: fitPX(-0) },
    pv_1: { paddingVertical: fitPX(-1) },
    pv_2: { paddingVertical: fitPX(-2) },
    pv_3: { paddingVertical: fitPX(-3) },
    pv_4: { paddingVertical: fitPX(-4) },
    pv_5: { paddingVertical: fitPX(-5) },
    pv_6: { paddingVertical: fitPX(-6) },
    pv_7: { paddingVertical: fitPX(-7) },
    pv_8: { paddingVertical: fitPX(-8) },
    pv_9: { paddingVertical: fitPX(-9) },
    pv_10: { paddingVertical: fitPX(-10) },
    pv_11: { paddingVertical: fitPX(-11) },
    pv_12: { paddingVertical: fitPX(-12) },
    pv_13: { paddingVertical: fitPX(-13) },
    pv_14: { paddingVertical: fitPX(-14) },
    pv_15: { paddingVertical: fitPX(-15) },
    pv_16: { paddingVertical: fitPX(-16) },
    pv_17: { paddingVertical: fitPX(-17) },
    pv_18: { paddingVertical: fitPX(-18) },
    pv_19: { paddingVertical: fitPX(-19) },
    pv_20: { paddingVertical: fitPX(-20) },
    pv_21: { paddingVertical: fitPX(-21) },
    pv_22: { paddingVertical: fitPX(-22) },
    pv_23: { paddingVertical: fitPX(-23) },
    pv_24: { paddingVertical: fitPX(-24) },
    pv_25: { paddingVertical: fitPX(-25) },
    pv_26: { paddingVertical: fitPX(-26) },
    pv_27: { paddingVertical: fitPX(-27) },
    pv_28: { paddingVertical: fitPX(-28) },
    pv_29: { paddingVertical: fitPX(-29) },
    pv_30: { paddingVertical: fitPX(-30) },

    pt: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            paddingTop: fitPX(number)
        }
    },
    pt0: { paddingTop: fitPX(0) },
    pt1: { paddingTop: fitPX(1) },
    pt2: { paddingTop: fitPX(2) },
    pt3: { paddingTop: fitPX(3) },
    pt4: { paddingTop: fitPX(4) },
    pt5: { paddingTop: fitPX(5) },
    pt6: { paddingTop: fitPX(6) },
    pt7: { paddingTop: fitPX(7) },
    pt8: { paddingTop: fitPX(8) },
    pt9: { paddingTop: fitPX(9) },
    pt10: { paddingTop: fitPX(10) },
    pt11: { paddingTop: fitPX(11) },
    pt12: { paddingTop: fitPX(12) },
    pt13: { paddingTop: fitPX(13) },
    pt14: { paddingTop: fitPX(14) },
    pt15: { paddingTop: fitPX(15) },
    pt16: { paddingTop: fitPX(16) },
    pt17: { paddingTop: fitPX(17) },
    pt18: { paddingTop: fitPX(18) },
    pt19: { paddingTop: fitPX(19) },
    pt20: { paddingTop: fitPX(20) },
    pt21: { paddingTop: fitPX(21) },
    pt22: { paddingTop: fitPX(22) },
    pt23: { paddingTop: fitPX(23) },
    pt24: { paddingTop: fitPX(24) },
    pt25: { paddingTop: fitPX(25) },
    pt26: { paddingTop: fitPX(26) },
    pt27: { paddingTop: fitPX(27) },
    pt28: { paddingTop: fitPX(28) },
    pt29: { paddingTop: fitPX(29) },
    pt30: { paddingTop: fitPX(30) },

    pt_0: { paddingTop: fitPX(-0) },
    pt_1: { paddingTop: fitPX(-1) },
    pt_2: { paddingTop: fitPX(-2) },
    pt_3: { paddingTop: fitPX(-3) },
    pt_4: { paddingTop: fitPX(-4) },
    pt_5: { paddingTop: fitPX(-5) },
    pt_6: { paddingTop: fitPX(-6) },
    pt_7: { paddingTop: fitPX(-7) },
    pt_8: { paddingTop: fitPX(-8) },
    pt_9: { paddingTop: fitPX(-9) },
    pt_10: { paddingTop: fitPX(-10) },
    pt_11: { paddingTop: fitPX(-11) },
    pt_12: { paddingTop: fitPX(-12) },
    pt_13: { paddingTop: fitPX(-13) },
    pt_14: { paddingTop: fitPX(-14) },
    pt_15: { paddingTop: fitPX(-15) },
    pt_16: { paddingTop: fitPX(-16) },
    pt_17: { paddingTop: fitPX(-17) },
    pt_18: { paddingTop: fitPX(-18) },
    pt_19: { paddingTop: fitPX(-19) },
    pt_20: { paddingTop: fitPX(-20) },
    pt_21: { paddingTop: fitPX(-21) },
    pt_22: { paddingTop: fitPX(-22) },
    pt_23: { paddingTop: fitPX(-23) },
    pt_24: { paddingTop: fitPX(-24) },
    pt_25: { paddingTop: fitPX(-25) },
    pt_26: { paddingTop: fitPX(-26) },
    pt_27: { paddingTop: fitPX(-27) },
    pt_28: { paddingTop: fitPX(-28) },
    pt_29: { paddingTop: fitPX(-29) },
    pt_30: { paddingTop: fitPX(-30) },

    pr: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            paddingRight: fitPX(number)
        }
    },
    pr0: { paddingRight: fitPX(0) },
    pr1: { paddingRight: fitPX(1) },
    pr2: { paddingRight: fitPX(2) },
    pr3: { paddingRight: fitPX(3) },
    pr4: { paddingRight: fitPX(4) },
    pr5: { paddingRight: fitPX(5) },
    pr6: { paddingRight: fitPX(6) },
    pr7: { paddingRight: fitPX(7) },
    pr8: { paddingRight: fitPX(8) },
    pr9: { paddingRight: fitPX(9) },
    pr10: { paddingRight: fitPX(10) },
    pr11: { paddingRight: fitPX(11) },
    pr12: { paddingRight: fitPX(12) },
    pr13: { paddingRight: fitPX(13) },
    pr14: { paddingRight: fitPX(14) },
    pr15: { paddingRight: fitPX(15) },
    pr16: { paddingRight: fitPX(16) },
    pr17: { paddingRight: fitPX(17) },
    pr18: { paddingRight: fitPX(18) },
    pr19: { paddingRight: fitPX(19) },
    pr20: { paddingRight: fitPX(20) },
    pr21: { paddingRight: fitPX(21) },
    pr22: { paddingRight: fitPX(22) },
    pr23: { paddingRight: fitPX(23) },
    pr24: { paddingRight: fitPX(24) },
    pr25: { paddingRight: fitPX(25) },
    pr26: { paddingRight: fitPX(26) },
    pr27: { paddingRight: fitPX(27) },
    pr28: { paddingRight: fitPX(28) },
    pr29: { paddingRight: fitPX(29) },
    pr30: { paddingRight: fitPX(30) },

    pr_0: { paddingRight: fitPX(-0) },
    pr_1: { paddingRight: fitPX(-1) },
    pr_2: { paddingRight: fitPX(-2) },
    pr_3: { paddingRight: fitPX(-3) },
    pr_4: { paddingRight: fitPX(-4) },
    pr_5: { paddingRight: fitPX(-5) },
    pr_6: { paddingRight: fitPX(-6) },
    pr_7: { paddingRight: fitPX(-7) },
    pr_8: { paddingRight: fitPX(-8) },
    pr_9: { paddingRight: fitPX(-9) },
    pr_10: { paddingRight: fitPX(-10) },
    pr_11: { paddingRight: fitPX(-11) },
    pr_12: { paddingRight: fitPX(-12) },
    pr_13: { paddingRight: fitPX(-13) },
    pr_14: { paddingRight: fitPX(-14) },
    pr_15: { paddingRight: fitPX(-15) },
    pr_16: { paddingRight: fitPX(-16) },
    pr_17: { paddingRight: fitPX(-17) },
    pr_18: { paddingRight: fitPX(-18) },
    pr_19: { paddingRight: fitPX(-19) },
    pr_20: { paddingRight: fitPX(-20) },
    pr_21: { paddingRight: fitPX(-21) },
    pr_22: { paddingRight: fitPX(-22) },
    pr_23: { paddingRight: fitPX(-23) },
    pr_24: { paddingRight: fitPX(-24) },
    pr_25: { paddingRight: fitPX(-25) },
    pr_26: { paddingRight: fitPX(-26) },
    pr_27: { paddingRight: fitPX(-27) },
    pr_28: { paddingRight: fitPX(-28) },
    pr_29: { paddingRight: fitPX(-29) },
    pr_30: { paddingRight: fitPX(-30) },

    pb: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            paddingBottom: fitPX(number)
        }
    },
    pb0: { paddingBottom: fitPX(0) },
    pb1: { paddingBottom: fitPX(1) },
    pb2: { paddingBottom: fitPX(2) },
    pb3: { paddingBottom: fitPX(3) },
    pb4: { paddingBottom: fitPX(4) },
    pb5: { paddingBottom: fitPX(5) },
    pb6: { paddingBottom: fitPX(6) },
    pb7: { paddingBottom: fitPX(7) },
    pb8: { paddingBottom: fitPX(8) },
    pb9: { paddingBottom: fitPX(9) },
    pb10: { paddingBottom: fitPX(10) },
    pb11: { paddingBottom: fitPX(11) },
    pb12: { paddingBottom: fitPX(12) },
    pb13: { paddingBottom: fitPX(13) },
    pb14: { paddingBottom: fitPX(14) },
    pb15: { paddingBottom: fitPX(15) },
    pb16: { paddingBottom: fitPX(16) },
    pb17: { paddingBottom: fitPX(17) },
    pb18: { paddingBottom: fitPX(18) },
    pb19: { paddingBottom: fitPX(19) },
    pb20: { paddingBottom: fitPX(20) },
    pb21: { paddingBottom: fitPX(21) },
    pb22: { paddingBottom: fitPX(22) },
    pb23: { paddingBottom: fitPX(23) },
    pb24: { paddingBottom: fitPX(24) },
    pb25: { paddingBottom: fitPX(25) },
    pb26: { paddingBottom: fitPX(26) },
    pb27: { paddingBottom: fitPX(27) },
    pb28: { paddingBottom: fitPX(28) },
    pb29: { paddingBottom: fitPX(29) },
    pb30: { paddingBottom: fitPX(30) },

    pb_0: { paddingBottom: fitPX(-0) },
    pb_1: { paddingBottom: fitPX(-1) },
    pb_2: { paddingBottom: fitPX(-2) },
    pb_3: { paddingBottom: fitPX(-3) },
    pb_4: { paddingBottom: fitPX(-4) },
    pb_5: { paddingBottom: fitPX(-5) },
    pb_6: { paddingBottom: fitPX(-6) },
    pb_7: { paddingBottom: fitPX(-7) },
    pb_8: { paddingBottom: fitPX(-8) },
    pb_9: { paddingBottom: fitPX(-9) },
    pb_10: { paddingBottom: fitPX(-10) },
    pb_11: { paddingBottom: fitPX(-11) },
    pb_12: { paddingBottom: fitPX(-12) },
    pb_13: { paddingBottom: fitPX(-13) },
    pb_14: { paddingBottom: fitPX(-14) },
    pb_15: { paddingBottom: fitPX(-15) },
    pb_16: { paddingBottom: fitPX(-16) },
    pb_17: { paddingBottom: fitPX(-17) },
    pb_18: { paddingBottom: fitPX(-18) },
    pb_19: { paddingBottom: fitPX(-19) },
    pb_20: { paddingBottom: fitPX(-20) },
    pb_21: { paddingBottom: fitPX(-21) },
    pb_22: { paddingBottom: fitPX(-22) },
    pb_23: { paddingBottom: fitPX(-23) },
    pb_24: { paddingBottom: fitPX(-24) },
    pb_25: { paddingBottom: fitPX(-25) },
    pb_26: { paddingBottom: fitPX(-26) },
    pb_27: { paddingBottom: fitPX(-27) },
    pb_28: { paddingBottom: fitPX(-28) },
    pb_29: { paddingBottom: fitPX(-29) },
    pb_30: { paddingBottom: fitPX(-30) },

    pl: function (number) {
        if (!isNumber(number)) {
            number = 0;
        }

        return {
            paddingLeft: fitPX(number)
        }
    },
    pl0: { paddingLeft: fitPX(0) },
    pl1: { paddingLeft: fitPX(1) },
    pl2: { paddingLeft: fitPX(2) },
    pl3: { paddingLeft: fitPX(3) },
    pl4: { paddingLeft: fitPX(4) },
    pl5: { paddingLeft: fitPX(5) },
    pl6: { paddingLeft: fitPX(6) },
    pl7: { paddingLeft: fitPX(7) },
    pl8: { paddingLeft: fitPX(8) },
    pl9: { paddingLeft: fitPX(9) },
    pl10: { paddingLeft: fitPX(10) },
    pl11: { paddingLeft: fitPX(11) },
    pl12: { paddingLeft: fitPX(12) },
    pl13: { paddingLeft: fitPX(13) },
    pl14: { paddingLeft: fitPX(14) },
    pl15: { paddingLeft: fitPX(15) },
    pl16: { paddingLeft: fitPX(16) },
    pl17: { paddingLeft: fitPX(17) },
    pl18: { paddingLeft: fitPX(18) },
    pl19: { paddingLeft: fitPX(19) },
    pl20: { paddingLeft: fitPX(20) },
    pl21: { paddingLeft: fitPX(21) },
    pl22: { paddingLeft: fitPX(22) },
    pl23: { paddingLeft: fitPX(23) },
    pl24: { paddingLeft: fitPX(24) },
    pl25: { paddingLeft: fitPX(25) },
    pl26: { paddingLeft: fitPX(26) },
    pl27: { paddingLeft: fitPX(27) },
    pl28: { paddingLeft: fitPX(28) },
    pl29: { paddingLeft: fitPX(29) },
    pl30: { paddingLeft: fitPX(30) },

    pl_0: { paddingLeft: fitPX(-0) },
    pl_1: { paddingLeft: fitPX(-1) },
    pl_2: { paddingLeft: fitPX(-2) },
    pl_3: { paddingLeft: fitPX(-3) },
    pl_4: { paddingLeft: fitPX(-4) },
    pl_5: { paddingLeft: fitPX(-5) },
    pl_6: { paddingLeft: fitPX(-6) },
    pl_7: { paddingLeft: fitPX(-7) },
    pl_8: { paddingLeft: fitPX(-8) },
    pl_9: { paddingLeft: fitPX(-9) },
    pl_10: { paddingLeft: fitPX(-10) },
    pl_11: { paddingLeft: fitPX(-11) },
    pl_12: { paddingLeft: fitPX(-12) },
    pl_13: { paddingLeft: fitPX(-13) },
    pl_14: { paddingLeft: fitPX(-14) },
    pl_15: { paddingLeft: fitPX(-15) },
    pl_16: { paddingLeft: fitPX(-16) },
    pl_17: { paddingLeft: fitPX(-17) },
    pl_18: { paddingLeft: fitPX(-18) },
    pl_19: { paddingLeft: fitPX(-19) },
    pl_20: { paddingLeft: fitPX(-20) },
    pl_21: { paddingLeft: fitPX(-21) },
    pl_22: { paddingLeft: fitPX(-22) },
    pl_23: { paddingLeft: fitPX(-23) },
    pl_24: { paddingLeft: fitPX(-24) },
    pl_25: { paddingLeft: fitPX(-25) },
    pl_26: { paddingLeft: fitPX(-26) },
    pl_27: { paddingLeft: fitPX(-27) },
    pl_28: { paddingLeft: fitPX(-28) },
    pl_29: { paddingLeft: fitPX(-29) },
    pl_30: { paddingLeft: fitPX(-30) },
};