
export default {
    fz0: { fontSize: 0 },
    fz1: { fontSize: 1 },
    fz2: { fontSize: 2 },
    fz3: { fontSize: 3 },
    fz4: { fontSize: 4 },
    fz5: { fontSize: 5 },
    fz6: { fontSize: 6 },
    fz7: { fontSize: 7 },
    fz8: { fontSize: 8 },
    fz9: { fontSize: 9 },
    fz10: { fontSize: 10 },
    fz11: { fontSize: 11 },
    fz12: { fontSize: 12 },
    fz13: { fontSize: 13 },
    fz14: { fontSize: 14 },
    fz15: { fontSize: 15 },
    fz16: { fontSize: 16 },
    fz17: { fontSize: 17 },
    fz18: { fontSize: 18 },
    fz19: { fontSize: 19 },
    fz20: { fontSize: 20 },
    fz21: { fontSize: 21 },
    fz22: { fontSize: 22 },
    fz23: { fontSize: 23 },
    fz24: { fontSize: 24 },
    fz25: { fontSize: 25 },
    fz26: { fontSize: 26 },
    fz27: { fontSize: 27 },
    fz28: { fontSize: 28 },
    fz29: { fontSize: 29 },
    fz30: { fontSize: 30 },

    lh0: { lineHeight: 0 },
    lh1: { lineHeight: 1 },
    lh2: { lineHeight: 2 },
    lh3: { lineHeight: 3 },
    lh4: { lineHeight: 4 },
    lh5: { lineHeight: 5 },
    lh6: { lineHeight: 6 },
    lh7: { lineHeight: 7 },
    lh8: { lineHeight: 8 },
    lh9: { lineHeight: 9 },
    lh10: { lineHeight: 10 },
    lh11: { lineHeight: 11 },
    lh12: { lineHeight: 12 },
    lh13: { lineHeight: 13 },
    lh14: { lineHeight: 14 },
    lh15: { lineHeight: 15 },
    lh16: { lineHeight: 16 },
    lh17: { lineHeight: 17 },
    lh18: { lineHeight: 18 },
    lh19: { lineHeight: 19 },
    lh20: { lineHeight: 20 },
    lh21: { lineHeight: 21 },
    lh22: { lineHeight: 22 },
    lh23: { lineHeight: 23 },
    lh24: { lineHeight: 24 },
    lh25: { lineHeight: 25 },
    lh26: { lineHeight: 26 },
    lh27: { lineHeight: 27 },
    lh28: { lineHeight: 28 },
    lh29: { lineHeight: 29 },
    lh30: { lineHeight: 30 },

    m0: { marginHorizontal: 0, marginVertical: 0 },
    m1: { marginHorizontal: 1, marginVertical: 1 },
    m2: { marginHorizontal: 2, marginVertical: 2 },
    m3: { marginHorizontal: 3, marginVertical: 3 },
    m4: { marginHorizontal: 4, marginVertical: 4 },
    m5: { marginHorizontal: 5, marginVertical: 5 },
    m6: { marginHorizontal: 6, marginVertical: 6 },
    m7: { marginHorizontal: 7, marginVertical: 7 },
    m8: { marginHorizontal: 8, marginVertical: 8 },
    m9: { marginHorizontal: 9, marginVertical: 9 },
    m10: { marginHorizontal: 10, marginVertical: 10 },
    m11: { marginHorizontal: 11, marginVertical: 11 },
    m12: { marginHorizontal: 12, marginVertical: 12 },
    m13: { marginHorizontal: 13, marginVertical: 13 },
    m14: { marginHorizontal: 14, marginVertical: 14 },
    m15: { marginHorizontal: 15, marginVertical: 15 },
    m16: { marginHorizontal: 16, marginVertical: 16 },
    m17: { marginHorizontal: 17, marginVertical: 17 },
    m18: { marginHorizontal: 18, marginVertical: 18 },
    m19: { marginHorizontal: 19, marginVertical: 19 },
    m20: { marginHorizontal: 20, marginVertical: 20 },
    m21: { marginHorizontal: 21, marginVertical: 21 },
    m22: { marginHorizontal: 22, marginVertical: 22 },
    m23: { marginHorizontal: 23, marginVertical: 23 },
    m24: { marginHorizontal: 24, marginVertical: 24 },
    m25: { marginHorizontal: 25, marginVertical: 25 },
    m26: { marginHorizontal: 26, marginVertical: 26 },
    m27: { marginHorizontal: 27, marginVertical: 27 },
    m28: { marginHorizontal: 28, marginVertical: 28 },
    m29: { marginHorizontal: 29, marginVertical: 29 },
    m30: { marginHorizontal: 30, marginVertical: 30 },

    mh0: { marginHorizontal: 0 },
    mh1: { marginHorizontal: 1 },
    mh2: { marginHorizontal: 2 },
    mh3: { marginHorizontal: 3 },
    mh4: { marginHorizontal: 4 },
    mh5: { marginHorizontal: 5 },
    mh6: { marginHorizontal: 6 },
    mh7: { marginHorizontal: 7 },
    mh8: { marginHorizontal: 8 },
    mh9: { marginHorizontal: 9 },
    mh10: { marginHorizontal: 10 },
    mh11: { marginHorizontal: 11 },
    mh12: { marginHorizontal: 12 },
    mh13: { marginHorizontal: 13 },
    mh14: { marginHorizontal: 14 },
    mh15: { marginHorizontal: 15 },
    mh16: { marginHorizontal: 16 },
    mh17: { marginHorizontal: 17 },
    mh18: { marginHorizontal: 18 },
    mh19: { marginHorizontal: 19 },
    mh20: { marginHorizontal: 20 },
    mh21: { marginHorizontal: 21 },
    mh22: { marginHorizontal: 22 },
    mh23: { marginHorizontal: 23 },
    mh24: { marginHorizontal: 24 },
    mh25: { marginHorizontal: 25 },
    mh26: { marginHorizontal: 26 },
    mh27: { marginHorizontal: 27 },
    mh28: { marginHorizontal: 28 },
    mh29: { marginHorizontal: 29 },
    mh30: { marginHorizontal: 30 },

    mv0: { marginVertical: 0 },
    mv1: { marginVertical: 1 },
    mv2: { marginVertical: 2 },
    mv3: { marginVertical: 3 },
    mv4: { marginVertical: 4 },
    mv5: { marginVertical: 5 },
    mv6: { marginVertical: 6 },
    mv7: { marginVertical: 7 },
    mv8: { marginVertical: 8 },
    mv9: { marginVertical: 9 },
    mv10: { marginVertical: 10 },
    mv11: { marginVertical: 11 },
    mv12: { marginVertical: 12 },
    mv13: { marginVertical: 13 },
    mv14: { marginVertical: 14 },
    mv15: { marginVertical: 15 },
    mv16: { marginVertical: 16 },
    mv17: { marginVertical: 17 },
    mv18: { marginVertical: 18 },
    mv19: { marginVertical: 19 },
    mv20: { marginVertical: 20 },
    mv21: { marginVertical: 21 },
    mv22: { marginVertical: 22 },
    mv23: { marginVertical: 23 },
    mv24: { marginVertical: 24 },
    mv25: { marginVertical: 25 },
    mv26: { marginVertical: 26 },
    mv27: { marginVertical: 27 },
    mv28: { marginVertical: 28 },
    mv29: { marginVertical: 29 },
    mv30: { marginVertical: 30 },

    mt0: { marginTop: 0 },
    mt1: { marginTop: 1 },
    mt2: { marginTop: 2 },
    mt3: { marginTop: 3 },
    mt4: { marginTop: 4 },
    mt5: { marginTop: 5 },
    mt6: { marginTop: 6 },
    mt7: { marginTop: 7 },
    mt8: { marginTop: 8 },
    mt9: { marginTop: 9 },
    mt10: { marginTop: 10 },
    mt11: { marginTop: 11 },
    mt12: { marginTop: 12 },
    mt13: { marginTop: 13 },
    mt14: { marginTop: 14 },
    mt15: { marginTop: 15 },
    mt16: { marginTop: 16 },
    mt17: { marginTop: 17 },
    mt18: { marginTop: 18 },
    mt19: { marginTop: 19 },
    mt20: { marginTop: 20 },
    mt21: { marginTop: 21 },
    mt22: { marginTop: 22 },
    mt23: { marginTop: 23 },
    mt24: { marginTop: 24 },
    mt25: { marginTop: 25 },
    mt26: { marginTop: 26 },
    mt27: { marginTop: 27 },
    mt28: { marginTop: 28 },
    mt29: { marginTop: 29 },
    mt30: { marginTop: 30 },

    mr0: { marginRight: 0 },
    mr1: { marginRight: 1 },
    mr2: { marginRight: 2 },
    mr3: { marginRight: 3 },
    mr4: { marginRight: 4 },
    mr5: { marginRight: 5 },
    mr6: { marginRight: 6 },
    mr7: { marginRight: 7 },
    mr8: { marginRight: 8 },
    mr9: { marginRight: 9 },
    mr10: { marginRight: 10 },
    mr11: { marginRight: 11 },
    mr12: { marginRight: 12 },
    mr13: { marginRight: 13 },
    mr14: { marginRight: 14 },
    mr15: { marginRight: 15 },
    mr16: { marginRight: 16 },
    mr17: { marginRight: 17 },
    mr18: { marginRight: 18 },
    mr19: { marginRight: 19 },
    mr20: { marginRight: 20 },
    mr21: { marginRight: 21 },
    mr22: { marginRight: 22 },
    mr23: { marginRight: 23 },
    mr24: { marginRight: 24 },
    mr25: { marginRight: 25 },
    mr26: { marginRight: 26 },
    mr27: { marginRight: 27 },
    mr28: { marginRight: 28 },
    mr29: { marginRight: 29 },
    mr30: { marginRight: 30 },

    mb0: { marginBottom: 0 },
    mb1: { marginBottom: 1 },
    mb2: { marginBottom: 2 },
    mb3: { marginBottom: 3 },
    mb4: { marginBottom: 4 },
    mb5: { marginBottom: 5 },
    mb6: { marginBottom: 6 },
    mb7: { marginBottom: 7 },
    mb8: { marginBottom: 8 },
    mb9: { marginBottom: 9 },
    mb10: { marginBottom: 10 },
    mb11: { marginBottom: 11 },
    mb12: { marginBottom: 12 },
    mb13: { marginBottom: 13 },
    mb14: { marginBottom: 14 },
    mb15: { marginBottom: 15 },
    mb16: { marginBottom: 16 },
    mb17: { marginBottom: 17 },
    mb18: { marginBottom: 18 },
    mb19: { marginBottom: 19 },
    mb20: { marginBottom: 20 },
    mb21: { marginBottom: 21 },
    mb22: { marginBottom: 22 },
    mb23: { marginBottom: 23 },
    mb24: { marginBottom: 24 },
    mb25: { marginBottom: 25 },
    mb26: { marginBottom: 26 },
    mb27: { marginBottom: 27 },
    mb28: { marginBottom: 28 },
    mb29: { marginBottom: 29 },
    mb30: { marginBottom: 30 },

    ml0: { marginLeft: 0 },
    ml1: { marginLeft: 1 },
    ml2: { marginLeft: 2 },
    ml3: { marginLeft: 3 },
    ml4: { marginLeft: 4 },
    ml5: { marginLeft: 5 },
    ml6: { marginLeft: 6 },
    ml7: { marginLeft: 7 },
    ml8: { marginLeft: 8 },
    ml9: { marginLeft: 9 },
    ml10: { marginLeft: 10 },
    ml11: { marginLeft: 11 },
    ml12: { marginLeft: 12 },
    ml13: { marginLeft: 13 },
    ml14: { marginLeft: 14 },
    ml15: { marginLeft: 15 },
    ml16: { marginLeft: 16 },
    ml17: { marginLeft: 17 },
    ml18: { marginLeft: 18 },
    ml19: { marginLeft: 19 },
    ml20: { marginLeft: 20 },
    ml21: { marginLeft: 21 },
    ml22: { marginLeft: 22 },
    ml23: { marginLeft: 23 },
    ml24: { marginLeft: 24 },
    ml25: { marginLeft: 25 },
    ml26: { marginLeft: 26 },
    ml27: { marginLeft: 27 },
    ml28: { marginLeft: 28 },
    ml29: { marginLeft: 29 },
    ml30: { marginLeft: 30 },

    p0: { paddingHorizontal: 0, paddingVertical: 0 },
    p1: { paddingHorizontal: 1, paddingVertical: 1 },
    p2: { paddingHorizontal: 2, paddingVertical: 2 },
    p3: { paddingHorizontal: 3, paddingVertical: 3 },
    p4: { paddingHorizontal: 4, paddingVertical: 4 },
    p5: { paddingHorizontal: 5, paddingVertical: 5 },
    p6: { paddingHorizontal: 6, paddingVertical: 6 },
    p7: { paddingHorizontal: 7, paddingVertical: 7 },
    p8: { paddingHorizontal: 8, paddingVertical: 8 },
    p9: { paddingHorizontal: 9, paddingVertical: 9 },
    p10: { paddingHorizontal: 10, paddingVertical: 10 },
    p11: { paddingHorizontal: 11, paddingVertical: 11 },
    p12: { paddingHorizontal: 12, paddingVertical: 12 },
    p13: { paddingHorizontal: 13, paddingVertical: 13 },
    p14: { paddingHorizontal: 14, paddingVertical: 14 },
    p15: { paddingHorizontal: 15, paddingVertical: 15 },
    p16: { paddingHorizontal: 16, paddingVertical: 16 },
    p17: { paddingHorizontal: 17, paddingVertical: 17 },
    p18: { paddingHorizontal: 18, paddingVertical: 18 },
    p19: { paddingHorizontal: 19, paddingVertical: 19 },
    p20: { paddingHorizontal: 20, paddingVertical: 20 },
    p21: { paddingHorizontal: 21, paddingVertical: 21 },
    p22: { paddingHorizontal: 22, paddingVertical: 22 },
    p23: { paddingHorizontal: 23, paddingVertical: 23 },
    p24: { paddingHorizontal: 24, paddingVertical: 24 },
    p25: { paddingHorizontal: 25, paddingVertical: 25 },
    p26: { paddingHorizontal: 26, paddingVertical: 26 },
    p27: { paddingHorizontal: 27, paddingVertical: 27 },
    p28: { paddingHorizontal: 28, paddingVertical: 28 },
    p29: { paddingHorizontal: 29, paddingVertical: 29 },
    p30: { paddingHorizontal: 30, paddingVertical: 30 },

    ph0: { paddingHorizontal: 0 },
    ph1: { paddingHorizontal: 1 },
    ph2: { paddingHorizontal: 2 },
    ph3: { paddingHorizontal: 3 },
    ph4: { paddingHorizontal: 4 },
    ph5: { paddingHorizontal: 5 },
    ph6: { paddingHorizontal: 6 },
    ph7: { paddingHorizontal: 7 },
    ph8: { paddingHorizontal: 8 },
    ph9: { paddingHorizontal: 9 },
    ph10: { paddingHorizontal: 10 },
    ph11: { paddingHorizontal: 11 },
    ph12: { paddingHorizontal: 12 },
    ph13: { paddingHorizontal: 13 },
    ph14: { paddingHorizontal: 14 },
    ph15: { paddingHorizontal: 15 },
    ph16: { paddingHorizontal: 16 },
    ph17: { paddingHorizontal: 17 },
    ph18: { paddingHorizontal: 18 },
    ph19: { paddingHorizontal: 19 },
    ph20: { paddingHorizontal: 20 },
    ph21: { paddingHorizontal: 21 },
    ph22: { paddingHorizontal: 22 },
    ph23: { paddingHorizontal: 23 },
    ph24: { paddingHorizontal: 24 },
    ph25: { paddingHorizontal: 25 },
    ph26: { paddingHorizontal: 26 },
    ph27: { paddingHorizontal: 27 },
    ph28: { paddingHorizontal: 28 },
    ph29: { paddingHorizontal: 29 },
    ph30: { paddingHorizontal: 30 },

    pv0: { paddingVertical: 0 },
    pv1: { paddingVertical: 1 },
    pv2: { paddingVertical: 2 },
    pv3: { paddingVertical: 3 },
    pv4: { paddingVertical: 4 },
    pv5: { paddingVertical: 5 },
    pv6: { paddingVertical: 6 },
    pv7: { paddingVertical: 7 },
    pv8: { paddingVertical: 8 },
    pv9: { paddingVertical: 9 },
    pv10: { paddingVertical: 10 },
    pv11: { paddingVertical: 11 },
    pv12: { paddingVertical: 12 },
    pv13: { paddingVertical: 13 },
    pv14: { paddingVertical: 14 },
    pv15: { paddingVertical: 15 },
    pv16: { paddingVertical: 16 },
    pv17: { paddingVertical: 17 },
    pv18: { paddingVertical: 18 },
    pv19: { paddingVertical: 19 },
    pv20: { paddingVertical: 20 },
    pv21: { paddingVertical: 21 },
    pv22: { paddingVertical: 22 },
    pv23: { paddingVertical: 23 },
    pv24: { paddingVertical: 24 },
    pv25: { paddingVertical: 25 },
    pv26: { paddingVertical: 26 },
    pv27: { paddingVertical: 27 },
    pv28: { paddingVertical: 28 },
    pv29: { paddingVertical: 29 },
    pv30: { paddingVertical: 30 },

    pt0: { paddingTop: 0 },
    pt1: { paddingTop: 1 },
    pt2: { paddingTop: 2 },
    pt3: { paddingTop: 3 },
    pt4: { paddingTop: 4 },
    pt5: { paddingTop: 5 },
    pt6: { paddingTop: 6 },
    pt7: { paddingTop: 7 },
    pt8: { paddingTop: 8 },
    pt9: { paddingTop: 9 },
    pt10: { paddingTop: 10 },
    pt11: { paddingTop: 11 },
    pt12: { paddingTop: 12 },
    pt13: { paddingTop: 13 },
    pt14: { paddingTop: 14 },
    pt15: { paddingTop: 15 },
    pt16: { paddingTop: 16 },
    pt17: { paddingTop: 17 },
    pt18: { paddingTop: 18 },
    pt19: { paddingTop: 19 },
    pt20: { paddingTop: 20 },
    pt21: { paddingTop: 21 },
    pt22: { paddingTop: 22 },
    pt23: { paddingTop: 23 },
    pt24: { paddingTop: 24 },
    pt25: { paddingTop: 25 },
    pt26: { paddingTop: 26 },
    pt27: { paddingTop: 27 },
    pt28: { paddingTop: 28 },
    pt29: { paddingTop: 29 },
    pt30: { paddingTop: 30 },

    pr0: { paddingRight: 0 },
    pr1: { paddingRight: 1 },
    pr2: { paddingRight: 2 },
    pr3: { paddingRight: 3 },
    pr4: { paddingRight: 4 },
    pr5: { paddingRight: 5 },
    pr6: { paddingRight: 6 },
    pr7: { paddingRight: 7 },
    pr8: { paddingRight: 8 },
    pr9: { paddingRight: 9 },
    pr10: { paddingRight: 10 },
    pr11: { paddingRight: 11 },
    pr12: { paddingRight: 12 },
    pr13: { paddingRight: 13 },
    pr14: { paddingRight: 14 },
    pr15: { paddingRight: 15 },
    pr16: { paddingRight: 16 },
    pr17: { paddingRight: 17 },
    pr18: { paddingRight: 18 },
    pr19: { paddingRight: 19 },
    pr20: { paddingRight: 20 },
    pr21: { paddingRight: 21 },
    pr22: { paddingRight: 22 },
    pr23: { paddingRight: 23 },
    pr24: { paddingRight: 24 },
    pr25: { paddingRight: 25 },
    pr26: { paddingRight: 26 },
    pr27: { paddingRight: 27 },
    pr28: { paddingRight: 28 },
    pr29: { paddingRight: 29 },
    pr30: { paddingRight: 30 },

    pb0: { paddingBottom: 0 },
    pb1: { paddingBottom: 1 },
    pb2: { paddingBottom: 2 },
    pb3: { paddingBottom: 3 },
    pb4: { paddingBottom: 4 },
    pb5: { paddingBottom: 5 },
    pb6: { paddingBottom: 6 },
    pb7: { paddingBottom: 7 },
    pb8: { paddingBottom: 8 },
    pb9: { paddingBottom: 9 },
    pb10: { paddingBottom: 10 },
    pb11: { paddingBottom: 11 },
    pb12: { paddingBottom: 12 },
    pb13: { paddingBottom: 13 },
    pb14: { paddingBottom: 14 },
    pb15: { paddingBottom: 15 },
    pb16: { paddingBottom: 16 },
    pb17: { paddingBottom: 17 },
    pb18: { paddingBottom: 18 },
    pb19: { paddingBottom: 19 },
    pb20: { paddingBottom: 20 },
    pb21: { paddingBottom: 21 },
    pb22: { paddingBottom: 22 },
    pb23: { paddingBottom: 23 },
    pb24: { paddingBottom: 24 },
    pb25: { paddingBottom: 25 },
    pb26: { paddingBottom: 26 },
    pb27: { paddingBottom: 27 },
    pb28: { paddingBottom: 28 },
    pb29: { paddingBottom: 29 },
    pb30: { paddingBottom: 30 },

    pl0: { paddingLeft: 0 },
    pl1: { paddingLeft: 1 },
    pl2: { paddingLeft: 2 },
    pl3: { paddingLeft: 3 },
    pl4: { paddingLeft: 4 },
    pl5: { paddingLeft: 5 },
    pl6: { paddingLeft: 6 },
    pl7: { paddingLeft: 7 },
    pl8: { paddingLeft: 8 },
    pl9: { paddingLeft: 9 },
    pl10: { paddingLeft: 10 },
    pl11: { paddingLeft: 11 },
    pl12: { paddingLeft: 12 },
    pl13: { paddingLeft: 13 },
    pl14: { paddingLeft: 14 },
    pl15: { paddingLeft: 15 },
    pl16: { paddingLeft: 16 },
    pl17: { paddingLeft: 17 },
    pl18: { paddingLeft: 18 },
    pl19: { paddingLeft: 19 },
    pl20: { paddingLeft: 20 },
    pl21: { paddingLeft: 21 },
    pl22: { paddingLeft: 22 },
    pl23: { paddingLeft: 23 },
    pl24: { paddingLeft: 24 },
    pl25: { paddingLeft: 25 },
    pl26: { paddingLeft: 26 },
    pl27: { paddingLeft: 27 },
    pl28: { paddingLeft: 28 },
    pl29: { paddingLeft: 29 },
    pl30: { paddingLeft: 30 },

    clr_black: { color: '#000' },
    clr_white: { color: '#fff' },
    clr_333: { color: '#333' },
    clr_999: { color: '#999' },
    clr_b2: { color: '#b2b2b2' },

    bgc_black: { backgroundColor: '#000' },
    bgc_white: { backgroundColor: '#fff' },
    bgc_red: { backgroundColor: 'red' },
    bgc_blue: { backgroundColor: 'blue' },

    flx_auto: { flex: 1 },
    flx_row: { flexDirection: 'row' },
    flx_column: { flexDirection: 'column' },
    flx_center: { justifyContent: 'center', alignItems: 'center' },

    // justify-content
    jc_start: { justifyContent: 'flex-start' },
    jc_end: { justifyContent: 'flex-end' },
    jc_center: { justifyContent: 'center' },
    jc_between: { justifyContent: 'space-between' },
    jc_around: { justifyContent: 'space-around' },

    // align-content
    ac_start: { alignContent: 'flex-start' },
    ac_end: { alignContent: 'flex-end' },
    ac_center: { alignContent: 'center' },
    ac_between: { alignContent: 'space-between' },
    ac_around: { alignContent: 'space-around' },
    ac_around: { alignContent: 'stretch' },

    // align-items
    ai_start: { alignItems: 'flex-start' },
    ai_end: { alignItems: 'flex-end' },
    ai_center: { alignItems: 'center' },
    ai_baseline : { alignItems: 'baseline' },
    ai_stretch: { alignItems: 'stretch' },

    // align-self
    as_auto: { alignSelf: 'auto' },
    as_start: { alignSelf: 'flex-start' },
    as_end: { alignSelf: 'flex-end' },
    as_center: { alignSelf: 'center' },
    as_baseline : { alignSelf: 'baseline' },
    as_stretch: { alignSelf: 'stretch' },
    
};